[#VC - 193] Visualização de Produto
Elias-Neto/camel-ui pull request #28
Opened 2024-02-29 19:32 UTC by andersonalbuqq

Implementação do carrossel de imagens

novo carousel

finalização da seção de produtos

get id by patch param

2024-03-01 12:41 UTC, Elias-Neto requested changes

2024-03-01 12:41 UTC, Elias-Neto commented on src/pages/product/index.jsx
> +async function getProduct(id, setItem) {
As funções que fazem chamadas à APIs devem ficar na pasta `/hooks`.

Atualmente, dentro de /hooks temos /auth (onde ficam funções de Autenticação) e /dataCreating (onde ficam funções de Criação).

Nesse caso, tu vai criar, dentro de /hooks, uma nova pasta /dataFetching e criar um arquivo useFetchPruductByID.

Pra criar o código, toma como referência o /hooks/dataCreating/useCreateUser.js.

2024-03-01 12:41 UTC, Elias-Neto commented on src/pages/product/index.jsx
> +                  <Field as="select" name="quantity">
Ta aí uma questão: Como vamo trabalhar com esse valor de quantidade que o usuário pode selecionar?
- Vamo fixar um valor?
- Vamo salvar no BD?

Pore quanto, deixa fixo, mas vamo deixar isso mapeado.

2024-03-01 17:50 UTC, andersonalbuqq commented on src/pages/product/index.jsx
> +                  <Field as="select" name="quantity">
Pois é, tem que vir a quantidade disponivel do back, e de alguma forma a gente tem que consegir limitar isso no front no mercado livre fica assim
![Captura de tela 2024-03-01 144942](https://github.com/Elias-Neto/camel-ui/assets/99482145/17077d7d-ed41-4887-8573-6793beb85815)

2024-03-01 22:38 UTC, Elias-Neto commented on src/pages/product/index.jsx
> +                  <Field as="select" name="quantity">
Boa! Não tinha feito essa pesquisa de mercado pra poder levanter melhor esse requisito.

Vamo deixar isso mapeado pra colocar na esteira de produção em outro momento.

Por enquanto, deixa uma quantidade mockada mesmo.

2024-03-02 00:16 UTC, Elias-Neto commented on src/hooks/dataFetching/useFetchProductByID.js
> +    try {
@andersonalbuqq , mudei o formato da função pra seguir o pdrão utilizando async-await e não fetch.

Além disso, essas funções da API vão seguir esse padrão de try-catch-finaly.

2024-03-02 00:27 UTC, Elias-Neto commented
@andersonalbuqq , vi que tu criou as pastas inicando com letra minúscula. Vamo seguir o padrão de pasta de componente e de pasta de page, nois nomeia com a primeira letra maiúsculas.

2024-03-02 00:29 UTC, Elias-Neto approved these changes

2024-03-02 00:29 UTC, Elias-Neto commented on src/routes/index.jsx
> +          <Route path="/produto/:id" element={<Product />} />
@andersonalbuqq , vamo começar a fazer as rotas com nomes em português, pois isso fica visível pro usuário final que são usuários de língua portuguesa.

Internamente (pastas, arquivos, funções, variáveis...) continuam sendo feitos em inglês.

2024-03-02 00:29 UTC, Elias-Neto commented on src/hooks/dataFetching/useFetchProductByID.js
> +  const FetchProductById = async (id, successCallback, errorCallback) => {
@andersonalbuqq , mudei o formato da função pra seguir o pdrão utilizando async-await e não fetch.

Além disso, essas funções da API vão seguir esse padrão de try-catch-finaly.

2024-03-02 00:30 UTC, merged