[#VC-189]Listagem de Produtos da Home
Elias-Neto/camel-ui pull request #29
Opened 2024-02-29 22:57 UTC by Ricardo-Gomes-Junior

Adicionado Componente CardProduto.

2024-03-05 10:29 UTC, andersonalbuqq requested changes

2024-03-05 10:29 UTC, andersonalbuqq commented on src/components/common/Card/index.jsx
> +    <div>
Incluir a tag <Link> com rota dinâmia para o produto selecionado. Exemplo 

// <Link to={`${BaseUrl}/produto/${id}`}>Clique aqui</Link>

2024-03-05 10:29 UTC, andersonalbuqq commented on src/components/common/Card/styles.js
> +  width: 100%;
Rever o tamanho da imagem para ficar de acordo com o projeto

2024-03-05 10:29 UTC, andersonalbuqq commented on src/components/common/Card/styles.js
> +  color: ${({ theme }) => theme.COLORS.BLACK};
Rever a cor do preço (Alterar para laranja)

2024-03-05 10:29 UTC, andersonalbuqq commented on src/components/common/CardContainer/styles.js
> +  width: 90%;
Adicionar um max-width ou limitar o numero de produtos por linha

2024-03-08 23:34 UTC, Ricardo-Gomes-Junior commented on src/components/common/Card/styles.js
> +  width: 100%;
Corrigido!

2024-03-08 23:34 UTC, Ricardo-Gomes-Junior commented on src/components/common/Card/styles.js
> +  color: ${({ theme }) => theme.COLORS.BLACK};
Alterado!

2024-03-08 23:34 UTC, Ricardo-Gomes-Junior commented on src/components/common/CardContainer/styles.js
> +  width: 90%;
Adicionado!

2024-03-09 01:36 UTC, closed without merging