[#165] Componente de Botão
Elias-Neto/camel-ui pull request #3
Opened 2023-11-10 17:07 UTC by andersonalbuqq

criação do componente de botão

2023-11-11 19:16 UTC, Elias-Neto requested changes

2023-11-11 19:16 UTC, Elias-Neto commented on src/components/forms/submitButton/index.jsx
> +function SubmitButton(props) {
Mudar para o padrão de desestruturação das props:

`SubmitButton({ text, props2, props3 })`

2023-11-11 19:16 UTC, Elias-Neto commented on src/components/forms/submitButton/index.jsx
> +function SubmitButton(props) {
Esse componente de botão vai ser utilizado só nos formulários?  

- Se sim, então, blz chamar ele de SubmitButton. Além disso, se ele for sempre um botão de submit, nesse caso, seria bom então já deixar mockado o tipo do botão como `type="submit"`.

- Se não, então, é melhor não especificar o tipo do botão nem nome nem no type. Além disso, nesse caso, é bom analisar com mais calma se esse componente de botão não se encaixaria como um componente padrão (common), se realmente se encaixar, logo, tem que fazer o componente d euma forma a atender a necessidade de todos os cenários.

Ao meu ver, esse componente seria um common - pois dá pra usar ele: nos forms, no menu do usuário, na pagina de produto, na pagina de carrinho, de orçamento...

2023-11-11 19:16 UTC, Elias-Neto commented on src/components/forms/submitButton/styles.js
> +    filter: brightness(1.15);
Nos estilos globais, já tem o css para o hover de links (tag a) e botões (tag button).

```
  a, button {
    border: none;
    background: none;
    cursor: pointer;
    transition: filter 0.2s;
  }
  
  a:hover, button:hover {
    filter: brightness(0.9);
  }
```

Eu atulizei esses estilos globais recentemente, é só fazer um pull que tu consegue trazer essas alteração pra tua máquina.

2023-11-11 19:16 UTC, Elias-Neto commented on src/components/forms/submitButton/styles.js
> +  font-size: 1.6rem;
Essa propriedade já tá ssendo definida nos estilos globais e sendo aplicada para os button.

 ```
 body, input, textarea, button {
    font-family: "Inter", sans-serif;
    font-size: 1.6rem;
    scrollbar-gutter: stable;
  }
```

2023-11-12 11:25 UTC, andersonalbuqq commented on src/components/forms/submitButton/index.jsx
> +function SubmitButton(props) {
A princípio a ideia era que ele fosse usado em todos os lugares (por isso o type não está mocado, fiz a alteração e esqueci de mudar ai), mas o problema é que em cada lugar que ele foi definido está sendo usado uma formatação com alguma mudança de layout

2023-11-12 11:25 UTC, andersonalbuqq commented on src/components/forms/submitButton/styles.js
> +  font-size: 1.6rem;
Estava dando problema quando usei com a extensão .module.css, ai como estava apenas copiando e fazendo pequenos ajustes deve ter passado despercebido.

2023-11-12 11:25 UTC, andersonalbuqq commented on src/components/forms/submitButton/index.jsx
> +function SubmitButton(props) {
alterado

2023-11-12 11:25 UTC, andersonalbuqq commented on src/components/forms/submitButton/styles.js
> +    filter: brightness(1.15);
ok

2023-11-12 11:50 UTC, andersonalbuqq reviewed
Correções feitas.

2023-11-13 14:17 UTC, Elias-Neto commented
> Correções feitas.

Tu precisa fazer outro commit com essas novas alterações.

Tu faz um novo commit vazio só que coloca ":1" depois do id da task, pra deixar claro que é o commit referente à uma alteração de uma Review. O comando seria assim: git commit -m "[#165:1] Componente de Botão" --allow-empty"

Depois disso é o mesmo processo, trabalha nas alterações, faz os commits necessários, faz o rebase e, por fim, o push novamente.

2023-11-13 15:34 UTC, Elias-Neto approved these changes

2023-11-13 15:34 UTC, merged